### ISSUE TITLE
Update compilation success message

### ISSUE THREAD

**Issue by bermudezmt** [twilio-professional-services/flex-preview-dialer#1]
```
You can now view plugin-flex-virtual-queue in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.21:3000
```

We should update this to reflect the actual plugin or solution name. Also, this used port 3000 by default when I ran this locally.

**Comment by kaiquelupo** [comment]
Sure. I forgot to change some names from the forked repository. I've just commit the changes
