### ISSUE TITLE
Example curl request for updating the Configuration object

### ISSUE THREAD

**Issue by bermudezmt** [twilio-professional-services/flex-preview-dialer#3]
curl request:
```
curl https://flex-api.twilio.com/v1/Configuration -X POST -u ACxxx:auth_token \
-H 'Content-Type: application/json' \
  -d '{
      "account_sid": "ACxxx",
      "attributes": {
          "serviceBaseUrl": "http://localhost:3000/",
          "campaigns": [{ name: "Collections", schedule: { week: ["Mon", "Wed"], startHour: "0100", endHour: "2200"}} ]
      }
  }'
```
Output:
```
{"code": 20001, "message": "Bad request", "more_info": "https://www.twilio.com/docs/errors/20001", "status": 400}
```

Sorry for opening this as an issue, but what am I doing wrong with this request? Reduced it down to one campaign, removed smart quotes, and I still get that error.

Additionally, can you update `appConfig.js` with the campaigns array details instead of using `curl`? It's not clear in the docs, and there are a few "attributes" related objects in the JSON response to `curl -X GET https://flex-api.twilio.com/v1/Configuration`.

**Comment by kaiquelupo** [comment]
Hey, you are right! Forgot to add double quotes to the properties inside the campaign array. This would do the trick but in the last plugin update, the way environment variables are handled changed and now we are using .env files. Please refer to the readme files to get more info on that. The "old issues" section is also explaining why this change was done.
