### ISSUE TITLE
Clarify section on adding the Campaigns information

### ISSUE THREAD

**Issue by bermudezmt** [twilio-professional-services/flex-preview-dialer#4]
If I'm understanding the docs, we'll need to provide the full JSON object and update it with our configuration values before sending a POST request:
https://www.twilio.com/docs/flex/ui/configuration#modifying-configuration-for-flextwiliocom

We might want to add a note for self-hosted versions as well and how they can update their UI configuration.

**Comment by kaiquelupo** [comment]
You are right. With the changes related to environment variables it is solved.
